
export enum Characters {
    Hagi = "Hagi",
    Bully = "Bully",
    Geek = "Geek",
    Nerd = "Nerd",
    PopGirl = "PopGirl",
    Freak = "Freak",
    Counselor = "Counselor",
    Stoner = "Stoner",
    Mom = "Mom",
    Dad = "Dad",
    Void = "Void",
    Teacher = "Teacher",
    Coach = "Coach",
    Lela = "Lela",
    ShyGirl = "ShyGirl",
    Principal = "Principal",
    StressFull = "StressFull",
    StressLess = "StressLess",
    SocialFull = "SocialFull",
    SocialLess = "SocialLess",
    ParentFull = "ParentFull",
    ParentLess = "ParentLess",
    GradeFull = "GradeFull",
    GradeEmpty = "GradeEmpty",
    MorningView = "MorningView",
    MorningView2 = "MorningView2",
    AfternoonView = "AfternoonView",
    AfternoonView2 = "AfternoonView2",
    AfternoonView3 = "AfternoonView3",
    EveningView = "EveningView",
    EveningView2 = "EveningView2",
    EveningView3 = "EveningView3",
    DreamBoi = "DreamBoi",
    Tv = "Tv",
    Owl = "Owl",
    PinkOwl = "PinkOwl",
    Rich = "Rich",
    Hall = "Hall",
    DoorMan = "DoorMan",

}