
export enum Characters {
    Hagi = "Hagi",
    Bully = "Bully",
    Nerd = "Nerd",
    PopGirl = "PopGirl",
    Freak = "Freak",
    Counselor = "Counselor",
    Stoner = "Stoner",
    Mom = "Mom",
    Dad = "Dad",
    Void = "Void",
    Teacher = "Teacher",
    Coach = "Coach",
    Lela = "Lela",
    ShyGirl = "ShyGirl",
    Principal = "Principal",
    StressFull = "StressFull",
    StressLess = "StressLess",
    SocialFull = "SocialFull",
    SocialLess = "SocialLess",
    ParentFull = "ParentFull",
    ParentLess = "ParentLess",
    GradeFull = "GradeFull",
    GradeEmpty = "GradeEmpty",
    MorningView = "MorningView",
    MorningView2 = "MorningView2",
    AfternoonView = "AfternoonView",
    AfternoonView2 = "AfternoonView2",
    EveningView = "EveningView",
    EveningView2 = "EveningView2",
    DreamBoi = "DreamBoi",

}